import { Alert } from '@/db/schema';
import { columns } from './alert-table-columns';
import { DataTable } from './data-table';

export const alertsDummy: Alert[] = [
  {
    id: '1',
    type: 'Lonjakan Kasus IGD',
    district: 'Kebayoran Baru',
    status: 'Aktif',
    createdAt: new Date('2024-06-01T08:00:00Z'),
    updatedAt: new Date('2024-06-01T09:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.92 },
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    relatedSymptoms: ['Demam', 'Batuk'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Perlu investigasi lebih lanjut.',
  },
  {
    id: '2',
    type: 'Kasus Baru DBD',
    district: 'Cicendo',
    status: 'Selesai',
    createdAt: new Date('2024-05-28T10:00:00Z'),
    updatedAt: new Date('2024-05-29T11:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.75 },
    province: 'Jawa Barat',
    city: 'Bandung',
    relatedSymptoms: ['Demam', 'Diare'],
    reviewedBy: 'user-2',
    reviewedAt: new Date('2024-05-29T12:00:00Z'),
    notes: 'Kasus sudah ditangani.',
  },
  {
    id: '3',
    type: 'Kejadian Luar Biasa Chikungunya',
    district: 'Tebet',
    status: 'Aktif',
    createdAt: new Date('2024-06-02T07:30:00Z'),
    updatedAt: new Date('2024-06-02T08:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.88 },
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    relatedSymptoms: ['Radang', 'Pilek'],
    reviewedBy: null,
    reviewedAt: null,
    notes: null,
  },
  {
    id: '4',
    type: 'Peningkatan Kasus Tipes',
    district: 'Medan Baru',
    status: 'Ditolak',
    createdAt: new Date('2024-05-25T09:00:00Z'),
    updatedAt: new Date('2024-05-25T10:00:00Z'),
    aiAnalysis: { risk: 'rendah', confidence: 0.6 },
    province: 'Sumatera Utara',
    city: 'Medan',
    relatedSymptoms: ['Demam', 'Meriang'],
    reviewedBy: 'user-3',
    reviewedAt: new Date('2024-05-25T11:00:00Z'),
    notes: 'Tidak ditemukan bukti wabah.',
  },
  {
    id: '5',
    type: 'Wabah Hepatitis',
    district: 'Cipayung',
    status: 'Tertunda',
    createdAt: new Date('2024-06-03T06:00:00Z'),
    updatedAt: new Date('2024-06-03T07:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.7 },
    province: 'DKI Jakarta',
    city: 'Jakarta Timur',
    relatedSymptoms: ['Sakit Kepala', 'Batuk'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Menunggu konfirmasi.',
  },
  {
    id: '6',
    type: 'Wabah Campak',
    district: 'Sukolilo',
    status: 'Aktif',
    createdAt: new Date('2024-06-01T10:00:00Z'),
    updatedAt: new Date('2024-06-01T11:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.95 },
    province: 'Jawa Timur',
    city: 'Surabaya',
    relatedSymptoms: ['Demam', 'Diare', 'Meriang'],
    reviewedBy: null,
    reviewedAt: null,
    notes: null,
  },
  {
    id: '7',
    type: 'Lonjakan Kasus Flu Burung',
    district: 'Bekasi Barat',
    status: 'Selesai',
    createdAt: new Date('2024-05-30T08:00:00Z'),
    updatedAt: new Date('2024-05-30T09:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.8 },
    province: 'Jawa Barat',
    city: 'Bekasi',
    relatedSymptoms: ['Batuk', 'Pilek'],
    reviewedBy: 'user-4',
    reviewedAt: new Date('2024-05-30T10:00:00Z'),
    notes: 'Sudah diverifikasi.',
  },
  {
    id: '8',
    type: 'Kasus Baru Covid-19',
    district: 'Tangerang Selatan',
    status: 'Aktif',
    createdAt: new Date('2024-06-04T09:00:00Z'),
    updatedAt: new Date('2024-06-04T10:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.9 },
    province: 'Banten',
    city: 'Tangerang',
    relatedSymptoms: ['Demam', 'Radang'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Kasus baru terdeteksi.',
  },
  {
    id: '9',
    type: 'Kejadian Luar Biasa Diare',
    district: 'Bogor Tengah',
    status: 'Ditolak',
    createdAt: new Date('2024-05-27T07:00:00Z'),
    updatedAt: new Date('2024-05-27T08:00:00Z'),
    aiAnalysis: { risk: 'rendah', confidence: 0.55 },
    province: 'Jawa Barat',
    city: 'Bogor',
    relatedSymptoms: ['Sakit Perut', 'Asam Lambung'],
    reviewedBy: 'user-5',
    reviewedAt: new Date('2024-05-27T09:00:00Z'),
    notes: 'Tidak memenuhi kriteria.',
  },
  {
    id: '10',
    type: 'Peningkatan Kasus Demam Berdarah',
    district: 'Palembang Ilir',
    status: 'Tertunda',
    createdAt: new Date('2024-06-05T08:00:00Z'),
    updatedAt: new Date('2024-06-05T09:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.68 },
    province: 'Sumatera Selatan',
    city: 'Palembang',
    relatedSymptoms: ['Demam', 'Radang', 'Diare'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Menunggu hasil lab.',
  },
  {
    id: '11',
    type: 'Kebakaran',
    district: 'Cilandak',
    status: 'Aktif',
    createdAt: new Date('2024-06-06T08:00:00Z'),
    updatedAt: new Date('2024-06-06T09:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.93 },
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    relatedSymptoms: ['Asap', 'Panas'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Kebakaran di area pemukiman.',
  },
  {
    id: '12',
    type: 'Banjir',
    district: 'Kramat Jati',
    status: 'Tertunda',
    createdAt: new Date('2024-06-07T07:00:00Z'),
    updatedAt: new Date('2024-06-07T08:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.72 },
    province: 'DKI Jakarta',
    city: 'Jakarta Timur',
    relatedSymptoms: ['Air Tinggi', 'Evakuasi'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Banjir akibat hujan deras.',
  },
  {
    id: '13',
    type: 'Tanah Longsor',
    district: 'Lembang',
    status: 'Aktif',
    createdAt: new Date('2024-06-08T06:00:00Z'),
    updatedAt: new Date('2024-06-08T07:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.89 },
    province: 'Jawa Barat',
    city: 'Bandung',
    relatedSymptoms: ['Tanah Bergerak', 'Kerusakan'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Tanah longsor di daerah perbukitan.',
  },
  {
    id: '14',
    type: 'Polusi Udara',
    district: 'Cengkareng',
    status: 'Selesai',
    createdAt: new Date('2024-06-09T09:00:00Z'),
    updatedAt: new Date('2024-06-09T10:00:00Z'),
    aiAnalysis: { risk: 'rendah', confidence: 0.65 },
    province: 'DKI Jakarta',
    city: 'Jakarta Barat',
    relatedSymptoms: ['Asap', 'Bau'],
    reviewedBy: 'user-6',
    reviewedAt: new Date('2024-06-09T11:00:00Z'),
    notes: 'Polusi udara sudah menurun.',
  },
  {
    id: '15',
    type: 'Kecelakaan Lalu Lintas',
    district: 'Pasar Minggu',
    status: 'Ditolak',
    createdAt: new Date('2024-06-10T08:00:00Z'),
    updatedAt: new Date('2024-06-10T09:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.7 },
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    relatedSymptoms: ['Cedera', 'Kemacetan'],
    reviewedBy: 'user-7',
    reviewedAt: new Date('2024-06-10T10:00:00Z'),
    notes: 'Tidak ada korban jiwa.',
  },
];

export default function Alerts() {
  // const alerts = await getAllAlerts()

  return (
    <div className="flex-1 flex flex-col">
      <header className="border-b border-border p-4">
        <h1 className="text-center text-xl font-semibold">Peringatan Dini</h1>
      </header>
      <main className="flex-1 p-8">
        <DataTable columns={columns} data={alertsDummy} />
      </main>
    </div>
  );
}
