import { Alert } from '@/db/schema';
import { columns } from './alert-table-columns';
import { DataTable } from './data-table';

export const alertsDummy: Alert[] = [
  {
    id: '1',
    type: 'Lonjakan Kasus IGD',
    district: 'Kebayoran Baru',
    status: 'Aktif',
    createdAt: new Date('2024-06-01T08:00:00Z'),
    updatedAt: new Date('2024-06-01T09:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.92 },
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    relatedSymptoms: ['Demam', 'Batuk'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Perlu investigasi lebih lanjut.',
  },
  {
    id: '2',
    type: 'Wabah DBD',
    district: 'Cicendo',
    status: 'Selesai',
    createdAt: new Date('2024-05-28T10:00:00Z'),
    updatedAt: new Date('2024-05-29T11:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.75 },
    province: 'Jawa Barat',
    city: 'Bandung',
    relatedSymptoms: ['Demam', 'Diare'],
    reviewedBy: 'user-2',
    reviewedAt: new Date('2024-05-29T12:00:00Z'),
    notes: 'Kasus sudah ditangani.',
  },
  {
    id: '3',
    type: 'Lonjakan Kasus IGD',
    district: 'Tebet',
    status: 'Aktif',
    createdAt: new Date('2024-06-02T07:30:00Z'),
    updatedAt: new Date('2024-06-02T08:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.88 },
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    relatedSymptoms: ['Radang', 'Pilek'],
    reviewedBy: null,
    reviewedAt: null,
    notes: null,
  },
  {
    id: '4',
    type: 'Wabah DBD',
    district: 'Medan Baru',
    status: 'Ditolak',
    createdAt: new Date('2024-05-25T09:00:00Z'),
    updatedAt: new Date('2024-05-25T10:00:00Z'),
    aiAnalysis: { risk: 'rendah', confidence: 0.6 },
    province: 'Sumatera Utara',
    city: 'Medan',
    relatedSymptoms: ['Demam', 'Meriang'],
    reviewedBy: 'user-3',
    reviewedAt: new Date('2024-05-25T11:00:00Z'),
    notes: 'Tidak ditemukan bukti wabah.',
  },
  {
    id: '5',
    type: 'Lonjakan Kasus IGD',
    district: 'Cipayung',
    status: 'Tertunda',
    createdAt: new Date('2024-06-03T06:00:00Z'),
    updatedAt: new Date('2024-06-03T07:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.7 },
    province: 'DKI Jakarta',
    city: 'Jakarta Timur',
    relatedSymptoms: ['Sakit Kepala', 'Batuk'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Menunggu konfirmasi.',
  },
  {
    id: '6',
    type: 'Wabah DBD',
    district: 'Sukolilo',
    status: 'Aktif',
    createdAt: new Date('2024-06-01T10:00:00Z'),
    updatedAt: new Date('2024-06-01T11:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.95 },
    province: 'Jawa Timur',
    city: 'Surabaya',
    relatedSymptoms: ['Demam', 'Diare', 'Meriang'],
    reviewedBy: null,
    reviewedAt: null,
    notes: null,
  },
  {
    id: '7',
    type: 'Lonjakan Kasus IGD',
    district: 'Bekasi Barat',
    status: 'Selesai',
    createdAt: new Date('2024-05-30T08:00:00Z'),
    updatedAt: new Date('2024-05-30T09:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.8 },
    province: 'Jawa Barat',
    city: 'Bekasi',
    relatedSymptoms: ['Batuk', 'Pilek'],
    reviewedBy: 'user-4',
    reviewedAt: new Date('2024-05-30T10:00:00Z'),
    notes: 'Sudah diverifikasi.',
  },
  {
    id: '8',
    type: 'Wabah DBD',
    district: 'Tangerang Selatan',
    status: 'Aktif',
    createdAt: new Date('2024-06-04T09:00:00Z'),
    updatedAt: new Date('2024-06-04T10:00:00Z'),
    aiAnalysis: { risk: 'tinggi', confidence: 0.9 },
    province: 'Banten',
    city: 'Tangerang',
    relatedSymptoms: ['Demam', 'Radang'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Kasus baru terdeteksi.',
  },
  {
    id: '9',
    type: 'Lonjakan Kasus IGD',
    district: 'Bogor Tengah',
    status: 'Ditolak',
    createdAt: new Date('2024-05-27T07:00:00Z'),
    updatedAt: new Date('2024-05-27T08:00:00Z'),
    aiAnalysis: { risk: 'rendah', confidence: 0.55 },
    province: 'Jawa Barat',
    city: 'Bogor',
    relatedSymptoms: ['Sakit Perut', 'Asam Lambung'],
    reviewedBy: 'user-5',
    reviewedAt: new Date('2024-05-27T09:00:00Z'),
    notes: 'Tidak memenuhi kriteria.',
  },
  {
    id: '10',
    type: 'Wabah DBD',
    district: 'Palembang Ilir',
    status: 'Tertunda',
    createdAt: new Date('2024-06-05T08:00:00Z'),
    updatedAt: new Date('2024-06-05T09:00:00Z'),
    aiAnalysis: { risk: 'sedang', confidence: 0.68 },
    province: 'Sumatera Selatan',
    city: 'Palembang',
    relatedSymptoms: ['Demam', 'Radang', 'Diare'],
    reviewedBy: null,
    reviewedAt: null,
    notes: 'Menunggu hasil lab.',
  },
];

export default function Warning() {
  // const alerts = await getAllAlerts()

  return (
    <div className="flex-1 flex flex-col">
      <header className="border-b border-border p-4">
        <h1 className="text-center text-xl font-semibold">Peringatan Dini</h1>
      </header>
      <main className="flex-1 p-8 *:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
        <DataTable columns={columns} data={alertsDummy} />
      </main>
    </div>
  );
}
